/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as backedGoldSol from "./BackedGold.sol";
export type { backedGoldSol };
import type * as mocks from "./mocks";
export type { mocks };
