/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BackedGold } from "./BackedGold";
export type { IBridge } from "./IBridge";
export type { IOracle } from "./IOracle";
