/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IOracle__factory } from "./IOracle__factory";
export { StubOracle__factory } from "./StubOracle__factory";
