/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBridge__factory } from "./IBridge__factory";
export { StubBridge__factory } from "./StubBridge__factory";
