/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BackedGold__factory } from "./BackedGold__factory";
export { IBridge__factory } from "./IBridge__factory";
export { IOracle__factory } from "./IOracle__factory";
