/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { Ownable } from "./@openzeppelin/contracts/access/Ownable";
export { Ownable__factory } from "./factories/@openzeppelin/contracts/access/Ownable__factory";
export type { IERC1155Errors } from "./@openzeppelin/contracts/interfaces/draft-IERC6093.sol/IERC1155Errors";
export { IERC1155Errors__factory } from "./factories/@openzeppelin/contracts/interfaces/draft-IERC6093.sol/IERC1155Errors__factory";
export type { IERC20Errors } from "./@openzeppelin/contracts/interfaces/draft-IERC6093.sol/IERC20Errors";
export { IERC20Errors__factory } from "./factories/@openzeppelin/contracts/interfaces/draft-IERC6093.sol/IERC20Errors__factory";
export type { IERC721Errors } from "./@openzeppelin/contracts/interfaces/draft-IERC6093.sol/IERC721Errors";
export { IERC721Errors__factory } from "./factories/@openzeppelin/contracts/interfaces/draft-IERC6093.sol/IERC721Errors__factory";
export type { ERC20 } from "./@openzeppelin/contracts/token/ERC20/ERC20";
export { ERC20__factory } from "./factories/@openzeppelin/contracts/token/ERC20/ERC20__factory";
export type { IERC20Metadata } from "./@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata";
export { IERC20Metadata__factory } from "./factories/@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata__factory";
export type { IERC20 } from "./@openzeppelin/contracts/token/ERC20/IERC20";
export { IERC20__factory } from "./factories/@openzeppelin/contracts/token/ERC20/IERC20__factory";
export type { BackedGold } from "./contracts/BackedGold.sol/BackedGold";
export { BackedGold__factory } from "./factories/contracts/BackedGold.sol/BackedGold__factory";
export type { IBridge } from "./contracts/BackedGold.sol/IBridge";
export { IBridge__factory } from "./factories/contracts/BackedGold.sol/IBridge__factory";
export type { IOracle } from "./contracts/BackedGold.sol/IOracle";
export { IOracle__factory } from "./factories/contracts/BackedGold.sol/IOracle__factory";
export type { MockERC20 } from "./contracts/mocks/MockERC20";
export { MockERC20__factory } from "./factories/contracts/mocks/MockERC20__factory";
export type { StubBridge } from "./contracts/mocks/StubBridge.sol/StubBridge";
export { StubBridge__factory } from "./factories/contracts/mocks/StubBridge.sol/StubBridge__factory";
export type { StubOracle } from "./contracts/mocks/StubOracle.sol/StubOracle";
export { StubOracle__factory } from "./factories/contracts/mocks/StubOracle.sol/StubOracle__factory";
