/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as stubBridgeSol from "./StubBridge.sol";
export * as stubOracleSol from "./StubOracle.sol";
export { MockERC20__factory } from "./MockERC20__factory";
