/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as stubBridgeSol from "./StubBridge.sol";
export type { stubBridgeSol };
import type * as stubOracleSol from "./StubOracle.sol";
export type { stubOracleSol };
export type { MockERC20 } from "./MockERC20";
